import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { PrismaClient } from '@prisma/client';
import { chromium, type Browser } from 'playwright';
import bcrypt from 'bcryptjs';
import { mkdir } from 'node:fs/promises';
import { USER_ROLES } from '../../src/lib/roles';
import { requiresMfa, totp } from '../../src/lib/auth/mfa-crypto';
const url = new URL(process.env.DATABASE_URL || 'http://invalid');
if (url.hostname !== '127.0.0.1' || url.port !== '55409' || url.pathname !== '/postgres') throw Error('Only isolated local DB 55409 is allowed');
const raw = new PrismaClient(), base = 'http://localhost:3209', password = 'SyntheticPass209!';
const schoolId = `browser209-${randomUUID()}`, campusId = randomUUID(); const accounts = new Map<string, {id:string;email:string}>(); let browser: Browser;
before(async () => { await raw.school.create({data:{id:schoolId,name:'Synthetic security school',slug:schoolId,regId:schoolId,contactEmail:'qa@example.invalid',city:'Synthetic',status:'ACTIVE',plan:'PRO'}}); await raw.campus.create({data:{id:campusId,schoolId,name:'Synthetic campus',regId:campusId,city:'Synthetic'}}); const hash=await bcrypt.hash(password,12); for(const role of USER_ROLES) {const id=randomUUID(),email=`${id}@example.invalid`;await raw.user.create({data:{id,email,password:hash,role,schoolId,campusId,fullName:'Synthetic QA',isActive:true,onboardingComplete:true}});accounts.set(role,{id,email});} await raw.authAttempt.deleteMany({}); await mkdir('/tmp/sko209-browser-evidence',{recursive:true}); browser=await chromium.launch({headless:true}); });
after(async () => {await browser?.close(); await raw.passwordReset.deleteMany({where:{userId:{in:[...accounts.values()].map(x=>x.id)}}}); await raw.school.delete({where:{id:schoolId}});await raw.$disconnect();});
for(const width of [1440,768,390]) for(const role of USER_ROLES) test(`${role} security flow at ${width}px`, async () => {
 const context=await browser.newContext({viewport:{width,height:900}});const page=await context.newPage(); const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const r=await context.request.post(base+'/api/auth/login',{data:{email:accounts.get(role)!.email,password}});assert.equal(r.status(),200,await r.text());
 const needsMfa=requiresMfa({role}); await page.goto(base+(needsMfa?'/protect-account':'/account/security'));await page.waitForLoadState('networkidle');
 await page.getByRole('heading',{name:needsMfa?'Protect your account':'Your active sessions'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(needsMfa) {await page.getByRole('button',{name:'Set up authenticator',exact:true}).click();await page.locator('#mfa-code').waitFor();await page.locator('#mfa-code').fill('000000');await page.locator('#mfa-code').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('button:focus').count(),1); for(const lang of ['ar','ur','en']) {await page.getByLabel('Language',{exact:true}).selectOption(lang);assert.equal(await page.locator('main').getAttribute('dir'),lang==='en'?'ltr':'rtl'); assert.equal(await page.locator('#mfa-code').getAttribute('dir'),'ltr');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);} }
 if(!needsMfa) for(const lang of ['ar','ur','en']) {await page.getByLabel('Language',{exact:true}).selectOption(lang);assert.equal(await page.locator('main').getAttribute('dir'),lang==='en'?'ltr':'rtl');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
 if(role==='SUPER_ADMIN'||role==='TEACHER')await page.screenshot({path:`/tmp/sko209-browser-evidence/${role.toLowerCase()}-${width}.png`,fullPage:true});assert.deepEqual(errors,[]);await context.close();
});
test('browser MFA enrollment completes only after code and explicit acknowledgement',async()=>{await raw.authAttempt.deleteMany({});const context=await browser.newContext();const page=await context.newPage();await context.request.post(base+'/api/auth/login',{data:{email:accounts.get('SUPER_ADMIN')!.email,password}});await page.goto(base+'/protect-account');await page.getByRole('button',{name:'Set up authenticator',exact:true}).click();const secret=await page.locator('code').innerText();await page.getByLabel('Authenticator or recovery code',{exact:true}).fill(totp(secret));await page.getByRole('button',{name:'Verify code',exact:true}).click();await page.locator('pre').waitFor();assert.equal(await page.getByRole('button',{name:'Enter workspace'}).isDisabled(),true);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Enter workspace'}).click();await page.waitForURL('**/super');assert.equal((await context.request.get(base+'/api/auth/session')).status(),200);await context.close();});
test('password reset via real server action revokes active sessions and consumes link',async()=>{await raw.authAttempt.deleteMany({});const context=await browser.newContext();const page=await context.newPage();const actor=accounts.get('TEACHER')!;await context.request.post(base+'/api/auth/login',{data:{email:actor.email,password}});const token=randomUUID();await raw.passwordReset.create({data:{email:actor.email,userId:actor.id,token,expiresAt:new Date(Date.now()+3600_000)}});await page.goto(base+'/forgot-password?token='+token);await page.locator('#new-password').waitFor();await page.locator('#new-password').fill('ChangedSynthetic209!');await page.locator('#confirm-password').fill('ChangedSynthetic209!');await page.getByRole('button',{name:'Save new password'}).click();await page.waitForURL('**/login');assert.equal((await context.request.get(base+'/api/auth/session')).status(),401);assert.equal(await raw.passwordReset.count({where:{token}}),0);assert.equal((await raw.user.findUniqueOrThrow({where:{id:actor.id}})).accessVersion,1);await context.close();});
