import { Document, Image, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { prisma } from "@/lib/db/prisma";
import { calculateWeightedGradeForClass } from "@/lib/academic/grade-calculator";

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 10,
    color: "#172033",
    fontFamily: "Helvetica",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#d7dde8",
    paddingBottom: 14,
    marginBottom: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logo: {
    width: 48,
    height: 48,
    borderRadius: 6,
  },
  headerText: {
    flex: 1,
  },
  schoolName: {
    fontSize: 18,
    fontWeight: 700,
  },
  muted: {
    color: "#667085",
    fontSize: 8,
  },
  title: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: 700,
  },
  grid: {
    flexDirection: "row",
    marginBottom: 14,
  },
  panel: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    padding: 10,
    marginRight: 12,
  },
  panelLast: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    padding: 10,
  },
  label: {
    color: "#667085",
    fontSize: 7,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  value: {
    fontSize: 10,
    fontWeight: 700,
    marginBottom: 6,
  },
  table: {
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    marginBottom: 14,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e8ecf3",
  },
  lastRow: {
    borderBottomWidth: 0,
  },
  th: {
    backgroundColor: "#f3f6fb",
    fontWeight: 700,
  },
  cell: {
    padding: 7,
    fontSize: 9,
  },
  flex2: {
    flex: 2,
  },
  flex1: {
    flex: 1,
  },
  right: {
    textAlign: "right",
  },
  center: {
    textAlign: "center",
  },
  footer: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#667085",
    fontSize: 8,
  },
  line: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  lineBold: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    fontWeight: 700,
  },
  lineTotal: {
    borderTopWidth: 1,
    borderTopColor: "#d7dde8",
    marginTop: 4,
    paddingTop: 6,
  },
});

type CampusInfo = {
  name: string;
  city: string;
  address: string | null;
  phone: string | null;
  board: string | null;
  logoUrl: string | null;
};

function Header({ campus }: { campus: CampusInfo }) {
  return (
    <View style={styles.header}>
      <View style={styles.headerRow}>
        {campus.logoUrl ? <Image src={campus.logoUrl} style={styles.logo} /> : null}
        <View style={styles.headerText}>
          <Text style={styles.schoolName}>{campus.name}</Text>
          <Text style={styles.muted}>
            {[campus.board, campus.city, campus.address, campus.phone].filter(Boolean).join(" | ")}
          </Text>
        </View>
      </View>
    </View>
  );
}

function Footer() {
  return (
    <View style={styles.footer}>
      <Text>Generated by SkooleeAI</Text>
      <Text>Authorized signature: ____________________</Text>
    </View>
  );
}

export async function generateClassGradesPdf(classId: string) {
  const cls = await prisma.class.findUnique({
    where: { id: classId },
    include: {
      campus: {
        select: { name: true, city: true, address: true, phone: true, board: true, logoUrl: true },
      },
    },
  });
  if (!cls) throw new Error("Class not found");

  const results = await calculateWeightedGradeForClass(classId, cls.campusId, cls.academicYear);
  const passed = results.filter((r) => r.passed).length;
  const className = [cls.name, cls.section].filter(Boolean).join(" ");

  const students = await prisma.student.findMany({
    where: { classId, campusId: cls.campusId },
    select: { id: true, rollNo: true },
  });
  const rollNoMap = new Map(students.map((s) => [s.id, s.rollNo]));

  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <Header campus={cls.campus} />
        <Text style={styles.title}>Final Grades — {className} ({cls.academicYear})</Text>
        <Text style={[styles.muted, { marginBottom: 12 }]}>
          Students: {results.length} &middot; Pass: {passed} &middot; Fail: {results.length - passed}
        </Text>
        <View style={styles.table}>
          <View style={[styles.row, styles.th]}>
            <Text style={[styles.cell, styles.flex1, styles.center]}>Rank</Text>
            <Text style={[styles.cell, styles.flex2]}>Student</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>Roll No</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>%</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>Grade</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>Status</Text>
          </View>
          {results.map((r, i) => {
            const rowStyle = i === results.length - 1 ? [styles.row, styles.lastRow] : styles.row;
            return (
              <View key={r.studentId} style={rowStyle}>
                <Text style={[styles.cell, styles.flex1, styles.center]}>#{r.rank}</Text>
                <Text style={[styles.cell, styles.flex2]}>{r.studentName}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{rollNoMap.get(r.studentId) || "-"}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{r.overallPercentage}%</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{r.overallGrade}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{r.passed ? "PASS" : "FAIL"}</Text>
              </View>
            );
          })}
        </View>
        <Footer />
      </Page>
    </Document>
  );
}

export async function generateInvoicePdf(invoiceId: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      campus: {
        select: { name: true, city: true, address: true, phone: true, board: true, logoUrl: true },
      },
      student: {
        include: { class: { select: { name: true, section: true } } },
      },
    },
  });
  if (!invoice) throw new Error("Invoice not found");

  const cls = invoice.student.class;
  const money = (n: number) => `Rs. ${n.toLocaleString()}`;

  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <Header campus={invoice.campus} />
        <Text style={styles.title}>Fee Invoice</Text>
        <View style={[styles.grid, { marginTop: 8 }]}>
          <View style={styles.panel}>
            <Text style={styles.label}>Student</Text>
            <Text style={styles.value}>{invoice.student.fullName}</Text>
            <Text style={styles.label}>Roll No</Text>
            <Text style={styles.value}>{invoice.student.rollNo}</Text>
            <Text style={styles.label}>Class</Text>
            <Text style={styles.value}>{[cls?.name, cls?.section].filter(Boolean).join(" ")}</Text>
          </View>
          <View style={styles.panelLast}>
            <Text style={styles.label}>Invoice No</Text>
            <Text style={styles.value}>{invoice.invoiceNumber || "-"}</Text>
            <Text style={styles.label}>Invoice Date</Text>
            <Text style={styles.value}>{invoice.invoiceDate.toLocaleDateString()}</Text>
            <Text style={styles.label}>Due Date</Text>
            <Text style={styles.value}>{invoice.dueDate.toLocaleDateString()}</Text>
            <Text style={styles.label}>Status</Text>
            <Text style={[styles.value, { textTransform: "uppercase" }]}>{invoice.status}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={[styles.row, styles.th]}>
            <Text style={[styles.cell, styles.flex2]}>Description</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>Amount</Text>
          </View>
          <View style={styles.row}>
            <Text style={[styles.cell, styles.flex2]}>Monthly Fee</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.monthlyFee)}</Text>
          </View>
          {invoice.oneTimeFees > 0 ? (
            <View style={styles.row}>
              <Text style={[styles.cell, styles.flex2]}>One-time Fees</Text>
              <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.oneTimeFees)}</Text>
            </View>
          ) : null}
          <View style={styles.row}>
            <Text style={[styles.cell, styles.flex2]}>Subtotal</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.subtotal)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={[styles.cell, styles.flex2]}>Discount</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.discountAmount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={[styles.cell, styles.flex2]}>Late Fee</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.lateFeeAmount)}</Text>
          </View>
          <View style={styles.row}>
            <Text style={[styles.cell, styles.flex2]}>Tax</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.taxAmount)}</Text>
          </View>
          <View style={[styles.row, styles.lastRow]}>
            <Text style={[styles.cell, styles.flex2]}>Total</Text>
            <Text style={[styles.cell, styles.flex1, styles.right]}>{money(invoice.totalAmount)}</Text>
          </View>
        </View>

        <View style={styles.line}>
          <Text style={styles.muted}>Total Paid</Text>
          <Text>{money(invoice.totalAmountPaid)}</Text>
        </View>
        <View style={[styles.lineBold, styles.lineTotal]}>
          <Text>Balance Due</Text>
          <Text>{money(invoice.balanceDue)}</Text>
        </View>
        <Footer />
      </Page>
    </Document>
  );
}

export async function generatePaymentPdf(paymentId: string) {
  const payment = await prisma.payment.findUnique({
    where: { id: paymentId },
    include: {
      campus: {
        select: { name: true, city: true, address: true, phone: true, board: true, logoUrl: true },
      },
      student: {
        include: { class: { select: { name: true, section: true } } },
      },
      invoice: {
        select: { invoiceNumber: true, totalAmount: true, totalAmountPaid: true, balanceDue: true, dueDate: true },
      },
      recorder: { select: { fullName: true } },
    },
  });
  if (!payment) throw new Error("Payment not found");

  const cls = payment.student.class;
  const money = (n: number) => `Rs. ${n.toLocaleString()}`;

  return renderToBuffer(
    <Document>
      <Page size="A4" style={styles.page}>
        <Header campus={payment.campus} />
        <Text style={styles.title}>Payment Receipt</Text>
        <View style={[styles.grid, { marginTop: 8 }]}>
          <View style={styles.panel}>
            <Text style={styles.label}>Student</Text>
            <Text style={styles.value}>{payment.student.fullName}</Text>
            <Text style={styles.label}>Roll No</Text>
            <Text style={styles.value}>{payment.student.rollNo}</Text>
            <Text style={styles.label}>Class</Text>
            <Text style={styles.value}>{[cls?.name, cls?.section].filter(Boolean).join(" ")}</Text>
          </View>
          <View style={styles.panelLast}>
            <Text style={styles.label}>Receipt No</Text>
            <Text style={styles.value}>{payment.receiptNo || "-"}</Text>
            <Text style={styles.label}>Payment Date</Text>
            <Text style={styles.value}>{payment.paymentDate.toLocaleDateString()}</Text>
            <Text style={styles.label}>Method</Text>
            <Text style={[styles.value, { textTransform: "uppercase" }]}>{payment.paymentMethod}</Text>
            <Text style={styles.label}>Reference</Text>
            <Text style={styles.value}>{payment.referenceNumber || "-"}</Text>
          </View>
        </View>

        <View style={styles.line}>
          <Text style={styles.muted}>Invoice No</Text>
          <Text>{payment.invoice.invoiceNumber || "-"}</Text>
        </View>
        <View style={styles.line}>
          <Text style={styles.muted}>Invoice Total</Text>
          <Text>{money(payment.invoice.totalAmount)}</Text>
        </View>
        <View style={[styles.lineBold, { marginTop: 6 }]}>
          <Text>Amount Paid</Text>
          <Text>{money(payment.amount)}</Text>
        </View>
        {payment.fineAmount > 0 ? (
          <View style={styles.line}>
            <Text style={styles.muted}>Fine</Text>
            <Text>{money(payment.fineAmount)}</Text>
          </View>
        ) : null}
        {payment.discountAmount > 0 ? (
          <View style={styles.line}>
            <Text style={styles.muted}>Discount</Text>
            <Text>- {money(payment.discountAmount)}</Text>
          </View>
        ) : null}
        {payment.note ? (
          <View style={styles.line}>
            <Text style={styles.muted}>Note</Text>
            <Text>{payment.note}</Text>
          </View>
        ) : null}
        <View style={styles.line}>
          <Text style={styles.muted}>Total Paid to Date</Text>
          <Text>{money(payment.invoice.totalAmountPaid)}</Text>
        </View>
        <View style={styles.line}>
          <Text style={styles.muted}>Balance Due</Text>
          <Text>{money(payment.invoice.balanceDue)}</Text>
        </View>
        {payment.recorder?.fullName ? (
          <View style={[styles.line, { marginTop: 6 }]}>
            <Text style={styles.muted}>Recorded By</Text>
            <Text>{payment.recorder.fullName}</Text>
          </View>
        ) : null}
        <Footer />
      </Page>
    </Document>
  );
}
