import { getLocalePackage } from "@/lib/locale/store";
import { localeTag } from "@/lib/locale/package";
import { translateUi } from "@/lib/locale/ui-messages";
import { renderLocaleInvoice, renderLocaleReceipt } from "@/lib/locale/invoice-pdf";
import { Document, Image, Page, StyleSheet, Text, View, renderToBuffer } from "@react-pdf/renderer";
import { prisma } from "@/lib/db/prisma";
import { calculateWeightedGradeForClass } from "@/lib/academic/grade-calculator";

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 10,
    color: "#172033",
    fontFamily: "Helvetica",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#d7dde8",
    paddingBottom: 14,
    marginBottom: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  logo: {
    width: 48,
    height: 48,
    borderRadius: 6,
  },
  headerText: {
    flex: 1,
  },
  schoolName: {
    fontSize: 18,
    fontWeight: 700,
  },
  muted: {
    color: "#667085",
    fontSize: 8,
  },
  title: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: 700,
  },
  grid: {
    flexDirection: "row",
    marginBottom: 14,
  },
  panel: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    padding: 10,
    marginRight: 12,
  },
  panelLast: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    padding: 10,
  },
  label: {
    color: "#667085",
    fontSize: 7,
    textTransform: "uppercase",
    marginBottom: 3,
  },
  value: {
    fontSize: 10,
    fontWeight: 700,
    marginBottom: 6,
  },
  table: {
    borderWidth: 1,
    borderColor: "#d7dde8",
    borderRadius: 6,
    marginBottom: 14,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e8ecf3",
  },
  lastRow: {
    borderBottomWidth: 0,
  },
  th: {
    backgroundColor: "#f3f6fb",
    fontWeight: 700,
  },
  cell: {
    padding: 7,
    fontSize: 9,
  },
  flex2: {
    flex: 2,
  },
  flex1: {
    flex: 1,
  },
  right: {
    textAlign: "right",
  },
  center: {
    textAlign: "center",
  },
  footer: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    color: "#667085",
    fontSize: 8,
  },
  line: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
  },
  lineBold: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    fontWeight: 700,
  },
  lineTotal: {
    borderTopWidth: 1,
    borderTopColor: "#d7dde8",
    marginTop: 4,
    paddingTop: 6,
  },
});

type CampusInfo = {
  name: string;
  city: string;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  board: string | null;
  logoUrl: string | null;
  school?: {
    name: string;
    logoUrl: string | null;
    phone: string | null;
    website: string | null;
    tagline: string | null;
    contactEmail: string | null;
  } | null;
};

function Header({ campus }: { campus: CampusInfo }) {
  const logo = campus.logoUrl || campus.school?.logoUrl || null;
  const tagline = campus.school?.tagline || null;
  const contactLine = [
    campus.board,
    campus.city,
    campus.address,
    campus.phone || campus.school?.phone,
    campus.email || campus.school?.contactEmail,
    campus.website || campus.school?.website,
  ].filter(Boolean).join(" | ");

  return (
    <View style={styles.header}>
      <View style={styles.headerRow}>
        {logo ? <Image src={logo} style={styles.logo} /> : null}
        <View style={styles.headerText}>
          <Text style={styles.schoolName}>{campus.name}</Text>
          {tagline ? <Text style={styles.muted}>{tagline}</Text> : null}
          <Text style={styles.muted}>{contactLine}</Text>
        </View>
      </View>
    </View>
  );
}

function Footer() {
  return (
    <View style={styles.footer}>
      <Text>Generated by SkooleeAI</Text>
      <Text>Authorized signature: ____________________</Text>
    </View>
  );
}

export async function generateClassGradesPdf(classId: string) {
  const cls = await prisma.class.findUnique({
    where: { id: classId },
    include: {
      campus: {
        select: { name: true, city: true, address: true, phone: true, email: true, website: true, board: true, logoUrl: true, school: { select: { name: true, logoUrl: true, phone: true, website: true, tagline: true, contactEmail: true } } },
      },
    },
  });
  if (!cls) throw new Error("Class not found");

  const locale = await getLocalePackage(cls.schoolId, cls.campusId);
  const t = (source: string) => translateUi(source, locale.language);
  const number = (value: number) => new Intl.NumberFormat(localeTag(locale),{useGrouping:false}).format(value);
  const rtl = locale.language !== "en";
  const results = await calculateWeightedGradeForClass(classId, cls.campusId, cls.academicYear);
  const passed = results.filter((r) => r.passed).length;
  const className = [cls.name, cls.section].filter(Boolean).join(" ");

  const students = await prisma.student.findMany({
    where: { classId, campusId: cls.campusId },
    select: { id: true, rollNo: true },
  });
  const rollNoMap = new Map(students.map((s) => [s.id, s.rollNo]));

  return renderToBuffer(
    <Document language={locale.language}>
      <Page size="A4" style={[styles.page,{fontFamily:`Receipt-${locale.language}`,direction:rtl?"rtl":"ltr",textAlign:rtl?"right":"left"}]}>
        <Header campus={cls.campus} />
        <Text style={styles.title}>{t("Final Grades")}</Text><Text style={{fontSize:12,marginBottom:8}}>{className}</Text><Text style={styles.muted}>{number(cls.academicYear)}</Text>
        <Text style={[styles.muted, { marginBottom: 12 }]}>
          {t("Students")}: {number(results.length)} · {t("Passed")}: {number(passed)} · {t("Failed")}: {number(results.length - passed)}
        </Text>
        <View style={styles.table}>
          <View style={[styles.row, styles.th,{flexDirection:rtl?"row-reverse":"row"}]}>
            <Text style={[styles.cell, styles.flex1, styles.center]}>{t("Rank")}</Text>
            <Text style={[styles.cell, styles.flex2]}>{t("Student")}</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>{t("Roll No")}</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>%</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>{t("Grade")}</Text>
            <Text style={[styles.cell, styles.flex1, styles.center]}>{t("Status")}</Text>
          </View>
          {results.map((r, i) => {
            const rowStyle = i === results.length - 1 ? [styles.row, styles.lastRow] : [styles.row];
            return (
              <View key={r.studentId} style={[...rowStyle,{flexDirection:rtl?"row-reverse":"row"}]}>
                <Text style={[styles.cell, styles.flex1, styles.center]}>#{number(r.rank)}</Text>
                <Text style={[styles.cell, styles.flex2]}>{r.studentName}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{rollNoMap.get(r.studentId) || "-"}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{number(r.overallPercentage)}%</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{r.overallGrade}</Text>
                <Text style={[styles.cell, styles.flex1, styles.center]}>{t(r.passed ? "Passed" : "Failed")}</Text>
              </View>
            );
          })}
        </View>
        <View style={styles.footer}><Text>SkooleeAI</Text><Text>{t("Authorized signature")}: ____________________</Text></View>
      </Page>
    </Document>
  );
}

export async function generateInvoicePdf(invoiceId: string) {
  const invoice = await prisma.invoice.findUnique({
    where: { id: invoiceId },
    include: {
      campus: {
        select: { name: true, city: true, address: true, phone: true, email: true, website: true, board: true, logoUrl: true, school: { select: { name: true, logoUrl: true, phone: true, website: true, tagline: true, contactEmail: true } } },
      },
      student: {
        include: { class: { select: { name: true, section: true } } },
      },
    },
  });
  if (!invoice) throw new Error("Invoice not found");

  return renderLocaleInvoice(invoice);
}

export async function generatePaymentPdf(paymentId: string) {
  const { immutablePaymentPdf } = await import("@/lib/fees/receipt");
  return immutablePaymentPdf(paymentId);
}
