"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { dashboardPathForRole } from "@/lib/roles";
const copy = {
 en: { title: "Protect your account", school: "School", setup: "Set up authenticator", code: "Authenticator or recovery code", verify: "Verify code", recovery: "Use a recovery code", instructions: "Add this secret to your authenticator app. Keep the device clock automatic. Your account stays restricted until you verify a code and save the recovery codes.", save: "Save these recovery codes somewhere private. Each works once. They cannot be displayed again. If you lose both your authenticator and codes, contact your school administrator; email alone cannot remove MFA.", ack: "I saved my recovery codes and understand how to recover access", finish: "Enter workspace", retry: "Start setup again", login: "Return to sign in", unavailable: "Sign in again to continue.", lost: "Keep your authenticator available. Each recovery code works once and ends your other sessions.", next: "Verify your account to continue." },
 ar: { title: "حماية حسابك", school: "المدرسة", setup: "إعداد تطبيق المصادقة", code: "رمز المصادقة أو الاسترداد", verify: "تحقق من الرمز", recovery: "استخدام رمز استرداد", instructions: "أضف هذا المفتاح إلى تطبيق المصادقة واضبط ساعة الجهاز تلقائياً. يبقى الحساب مقيداً حتى التحقق وحفظ رموز الاسترداد.", save: "احفظ رموز الاسترداد في مكان خاص. يستخدم كل رمز مرة واحدة ولا يمكن عرضه مجدداً. إذا فقدت التطبيق والرموز، تواصل مع مسؤول المدرسة؛ البريد وحده لا يلغي المصادقة.", ack: "حفظت رموز الاسترداد وفهمت طريقة استعادة الوصول", finish: "الدخول إلى مساحة العمل", retry: "بدء الإعداد مجدداً", login: "العودة لتسجيل الدخول", unavailable: "سجل الدخول مجدداً للمتابعة.", lost: "احتفظ بتطبيق المصادقة. يعمل كل رمز استرداد مرة واحدة وينهي جلساتك الأخرى.", next: "تحقق من حسابك للمتابعة." },
 ur: { title: "اپنے اکاؤنٹ کو محفوظ کریں", school: "اسکول", setup: "تصدیقی ایپ ترتیب دیں", code: "تصدیق یا بحالی کا کوڈ", verify: "کوڈ کی تصدیق", recovery: "بحالی کا کوڈ استعمال کریں", instructions: "یہ کلید اپنی تصدیقی ایپ میں شامل کریں اور آلے کی گھڑی خودکار رکھیں۔ کوڈ کی تصدیق اور بحالی کوڈ محفوظ ہونے تک رسائی محدود رہے گی۔", save: "بحالی کوڈ نجی جگہ محفوظ کریں۔ ہر کوڈ صرف ایک بار استعمال ہوتا ہے اور دوبارہ دکھایا نہیں جا سکتا۔ ایپ اور کوڈ دونوں کھو جائیں تو اسکول منتظم سے رابطہ کریں؛ صرف ای میل کافی نہیں۔", ack: "میں نے بحالی کوڈ محفوظ کر لیے اور بحالی کا طریقہ سمجھ لیا", finish: "ورک اسپیس میں داخل ہوں", retry: "ترتیب دوبارہ شروع کریں", login: "سائن ان پر واپس جائیں", unavailable: "جاری رکھنے کے لیے دوبارہ سائن ان کریں۔", lost: "اپنی تصدیقی ایپ محفوظ رکھیں۔ ہر بحالی کوڈ ایک بار کام کرتا اور دوسری نشستیں ختم کرتا ہے۔", next: "جاری رکھنے کے لیے اکاؤنٹ کی تصدیق کریں۔" }
};
export default function ProtectAccount() {
 const router = useRouter(); const [language, setLanguage] = useState<keyof typeof copy>("en"); const t = copy[language];
 const [status, setStatus] = useState<{ enrolled: boolean; school: string; awaitingAcknowledgement: boolean } | null>(null);
 const [secret, setSecret] = useState(""); const [codes, setCodes] = useState<string[]>([]); const [code, setCode] = useState(""); const [recovery, setRecovery] = useState(false); const [ack, setAck] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
 useEffect(() => { const lang = document.documentElement.lang; if (lang === "ar" || lang === "ur") setLanguage(lang); fetch("/api/auth/mfa", { cache: "no-store" }).then(async r => { const data = await r.json(); if (!r.ok) throw Error(data.error); setStatus(data); }).catch(e => setError(e.message)); }, []);
 async function send(action: string) { setBusy(true); setError(""); try { const r = await fetch("/api/auth/mfa", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, code, recovery, acknowledged: ack }) }); const data = await r.json(); if (!r.ok) throw Error(data.error || t.unavailable); if (data.secret) { setSecret(data.secret); setCodes([]); setAck(false); } if (data.recoveryCodes) { setCodes(data.recoveryCodes); setSecret(""); setCode(""); } if (data.user) router.replace(data.user.mustChangePassword ? "/first-login" : dashboardPathForRole(data.user.role)); } catch(e) { setError(e instanceof Error ? e.message : t.unavailable); } finally { setBusy(false); } }
 function submit(e: FormEvent) { e.preventDefault(); void send(status?.enrolled ? "challenge" : "verify-setup"); }
 return <main lang={language} dir={language === "en" ? "ltr" : "rtl"} className="min-h-screen bg-purple-50 p-4 sm:p-8"><section className="mx-auto max-w-lg rounded-2xl bg-white p-6 shadow-sm space-y-5"><select aria-label="Language" value={language} onChange={e => setLanguage(e.target.value as keyof typeof copy)} className="min-h-11 border rounded p-2"><option value="en">English</option><option value="ar">العربية</option><option value="ur">اردو</option></select><h1 className="text-2xl font-bold">{t.title}</h1><p>{status ? `${t.school}: ${status.school}` : t.next}</p>{error && <p role="alert" className="text-red-700">{error}</p>}{status && !status.enrolled && !secret && codes.length === 0 && <button disabled={busy} onClick={() => send("setup")} className="min-h-11 rounded bg-purple-700 text-white px-5">{status.awaitingAcknowledgement ? t.retry : t.setup}</button>}{secret && <><p>{t.instructions}</p><code dir="ltr" className="block break-all rounded bg-slate-100 p-4 select-all">{secret}</code></>}{(status?.enrolled || secret) && <form onSubmit={submit} className="space-y-4"><label className="block" htmlFor="mfa-code">{t.code}</label><input id="mfa-code" value={code} onChange={e => setCode(e.target.value)} autoComplete="one-time-code" dir="ltr" inputMode={recovery ? "text" : "numeric"} className="w-full min-h-12 rounded border p-3 text-xl" required aria-describedby="mfa-guidance"/><p id="mfa-guidance">{t.lost}</p>{status?.enrolled && <label className="flex gap-3 items-center min-h-11"><input type="checkbox" checked={recovery} onChange={e => { setRecovery(e.target.checked); setCode(""); }}/>{t.recovery}</label>}<button disabled={busy} className="min-h-11 rounded bg-purple-700 px-5 text-white">{t.verify}</button></form>}{codes.length > 0 && <><p>{t.save}</p><pre dir="ltr" className="overflow-x-auto rounded bg-slate-100 p-4 text-sm select-all">{codes.join("\n")}</pre><label className="flex items-start gap-3"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)} className="mt-1"/>{t.ack}</label><button disabled={!ack || busy} onClick={() => send("acknowledge")} className="min-h-11 rounded bg-purple-700 px-5 text-white disabled:opacity-50">{t.finish}</button></>}<Link href="/login" className="block underline min-h-11">{t.login}</Link></section></main>;
}
