import { translateUi } from "./ui-messages";
import path from "node:path";
import { Document, Font, Image, Page, Text, View, renderToBuffer, StyleSheet } from "@react-pdf/renderer";
import { defaultLocale, formatDateOnly, formatMoney, localePackageSchema } from "./package";
Font.register({ family: "LocaleArabic", fonts: [
 { src: path.join(process.cwd(), "public/fonts/NotoNaskhArabic-Regular.ttf"), fontWeight: 400 },
 { src: path.join(process.cwd(), "public/fonts/NotoNaskhArabic-Bold.ttf"), fontWeight: 700 },
] });
for (const language of ["en", "ar", "ur"]) Font.register({family:`Receipt-${language}`,fonts:[{src:path.join(process.cwd(),"public/fonts/NotoNaskhArabic-Regular.ttf"),fontWeight:400},{src:path.join(process.cwd(),"public/fonts/NotoNaskhArabic-Bold.ttf"),fontWeight:700}]});
const labels = {
 ur: {"invoice":"فیس کا بل","student":"طالب علم","roll":"رول نمبر","class":"جماعت","date":"بل کی تاریخ","due":"آخری تاریخ","monthlyFee":"ماہانہ فیس","oneTimeFees":"یک وقتی فیس","subtotal":"ذیلی مجموعہ","discountAmount":"رعایت","lateFeeAmount":"تاخیر کی فیس","taxAmount":"ٹیکس","totalAmount":"کل رقم","totalAmountPaid":"ادا شدہ رقم","balanceDue":"باقی رقم","signature":"مجاز دستخط","original":"بنیادی عیسوی تاریخ","generated":"تیار کردہ"},
 en: { invoice: "Fee invoice", student: "Student", roll: "Roll number", class: "Class", date: "Invoice date", due: "Due date", monthlyFee: "Monthly fee", oneTimeFees: "One-time fees", subtotal: "Subtotal", discountAmount: "Discount", lateFeeAmount: "Late fee", taxAmount: "Tax", totalAmount: "Total", totalAmountPaid: "Total paid", balanceDue: "Balance due", signature: "Authorized signature", original: "Underlying Gregorian date", generated: "Generated by" },
 ar: { invoice: "فاتورة الرسوم", student: "الطالب", roll: "رقم الطالب", class: "الصف", date: "تاريخ الفاتورة", due: "تاريخ الاستحقاق", monthlyFee: "الرسوم الشهرية", oneTimeFees: "رسوم لمرة واحدة", subtotal: "المجموع الفرعي", discountAmount: "الخصم", lateFeeAmount: "رسوم التأخير", taxAmount: "الضريبة", totalAmount: "الإجمالي", totalAmountPaid: "إجمالي المدفوع", balanceDue: "الرصيد المستحق", signature: "التوقيع المعتمد", original: "التاريخ الميلادي الأساسي", generated: "تم الإنشاء بواسطة" },
};
type InvoiceDocument = { invoiceNumber: string | null; currency: string; localeSnapshot: unknown; invoiceDate: Date; dueDate: Date; campus: { name: string; city?: string | null; address?: string | null; phone?: string | null; email?: string | null; website?: string | null; logoUrl?: string | null; school?: { logoUrl?: string | null; tagline?: string | null; phone?: string | null; contactEmail?: string | null; website?: string | null } | null }; student: { fullName: string; rollNo: string; class: { name: string; section: string | null } }; monthlyFee: number; oneTimeFees: number; subtotal: number; discountAmount: number; lateFeeAmount: number; taxAmount: number; totalAmount: number; totalAmountPaid: number; balanceDue: number };
const styles = StyleSheet.create({ page: { padding: 36, fontSize: 12, color: "#172033", fontFamily: "LocaleArabic" }, heading: { fontSize: 22, fontWeight: 700, marginBottom: 8 }, row: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#ddd", paddingVertical: 7, gap: 18 }, label: { flex: 1 }, value: { flex: 1 }, muted: { fontSize: 9, color: "#667085", marginTop: 12 } });
function DocumentHeader({ campus }: { campus: InvoiceDocument["campus"] }) {
 const logo=campus.logoUrl || campus.school?.logoUrl;
 const contact=[campus.city,campus.address,campus.phone || campus.school?.phone,campus.email || campus.school?.contactEmail,campus.website || campus.school?.website].filter(Boolean).join(" · ");
 return <View>{logo ? <Image src={logo} style={{width:40,height:40,objectFit:"contain",marginBottom:6}} /> : null}<Text style={styles.heading}>{campus.name}</Text>{campus.school?.tagline ? <Text style={styles.muted}>{campus.school.tagline}</Text> : null}{contact ? <Text style={[styles.muted,{marginTop:0,marginBottom:10}]}>{contact}</Text> : null}</View>;
}
export function renderLocaleInvoice(invoice: InvoiceDocument) {
 const parsed = localePackageSchema.safeParse(invoice.localeSnapshot);
 const policy = parsed.success ? parsed.data : defaultLocale;
 const t = labels[policy.language]; const rtl = policy.language !== "en";
 const rows: [string, string][] = [
 [t.student, invoice.student.fullName], [t.roll, invoice.student.rollNo], [t.class, [invoice.student.class.name, invoice.student.class.section].filter(Boolean).join(" ")],
 [t.date, formatDateOnly(invoice.invoiceDate.toISOString().slice(0, 10), policy)], [t.due, formatDateOnly(invoice.dueDate.toISOString().slice(0, 10), policy)],
 ...(["monthlyFee", "oneTimeFees", "subtotal", "discountAmount", "lateFeeAmount", "taxAmount", "totalAmount", "totalAmountPaid", "balanceDue"] as const).map((key): [string, string] => [t[key], formatMoney({ minor: invoice[key], currency: invoice.currency }, policy)]),
 ];
 return renderToBuffer(<Document language={policy.language}><Page size="A4" style={[styles.page, { direction: rtl ? "rtl" : "ltr", textAlign: rtl ? "right" : "left" }]}><DocumentHeader campus={invoice.campus} /><Text style={styles.heading}>{t.invoice}</Text><Text>{invoice.invoiceNumber || "—"}</Text>{rows.map(([label, value]) => <View key={label} style={[styles.row, { flexDirection: rtl ? "row-reverse" : "row" }]}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}<Text style={styles.muted}>{t.original}</Text><Text style={[styles.muted, { direction: "ltr", textAlign: "left" }]}>{invoice.invoiceDate.toISOString().slice(0, 10)} / {invoice.dueDate.toISOString().slice(0, 10)}</Text><Text style={styles.muted}>{t.signature}: ____________________</Text><View style={[styles.row, { borderBottomWidth: 0 }]}><Text style={[styles.muted, { direction: "ltr" }]}>SkooleeAI</Text><Text style={styles.muted}>{t.generated}</Text></View></Page></Document>);
}

type ReceiptDocument = {
 receiptNo: string | null; paymentDate: Date; paymentMethod: string; referenceNumber: string | null;
 amount: number; fineAmount: number; discountAmount: number; note: string | null;
 campus: InvoiceDocument["campus"]; student: InvoiceDocument["student"];
 invoice: Pick<InvoiceDocument, "invoiceNumber" | "currency" | "localeSnapshot" | "totalAmount" | "totalAmountPaid" | "balanceDue">;
 recorder: { fullName: string } | null;
};
export function renderLocaleReceipt(payment: ReceiptDocument) {
 const parsed = localePackageSchema.safeParse(payment.invoice.localeSnapshot);
 const policy = parsed.success ? parsed.data : defaultLocale;
 const rtl = policy.language !== "en";
 const t = (source: string) => translateUi(source, policy.language);
 const money = (minor: number) => formatMoney({minor, currency: payment.invoice.currency}, policy);
 const rows: [string,string][] = [
  [t("Student"),payment.student.fullName], [t("Roll No"),payment.student.rollNo],
  [t("Class"),[payment.student.class.name,payment.student.class.section].filter(Boolean).join(" ")],
  [t("Receipt No"),payment.receiptNo || "—"], [t("Payment Date"),formatDateOnly(payment.paymentDate.toISOString().slice(0,10),policy)],
  [t("Method"),t(payment.paymentMethod.toUpperCase())], [t("Reference"),payment.referenceNumber || "—"],
  [t("Invoice No"),payment.invoice.invoiceNumber || "—"], [t("Invoice Total"),money(payment.invoice.totalAmount)],
  [t("Amount Paid"),money(payment.amount)], [t("Fine"),money(payment.fineAmount)], [t("Discount"),money(payment.discountAmount)],
  [t("Total Paid to Date"),money(payment.invoice.totalAmountPaid)], [t("Balance Due"),money(payment.invoice.balanceDue)],
 ];
 if(payment.note)rows.push([t("Note"),payment.note]);
 if(payment.recorder)rows.push([t("Recorded By"),payment.recorder.fullName]);
 return renderToBuffer(<Document language={policy.language}><Page size="A4" style={[styles.page,{fontFamily:`Receipt-${policy.language}`,direction:rtl?"rtl":"ltr",textAlign:rtl?"right":"left"}]}><DocumentHeader campus={payment.campus} /><Text style={styles.heading}>{t("Payment Receipt")}</Text>{rows.map(([label,value])=><View key={label} style={[styles.row,{flexDirection:rtl?"row-reverse":"row"}]}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}<Text style={styles.muted}>{payment.paymentDate.toISOString().slice(0,10)}</Text><Text style={styles.muted}>SkooleeAI</Text></Page></Document>);
}
