import path from "node:path";
import { Document, Font, Page, Text, View, renderToBuffer, StyleSheet } from "@react-pdf/renderer";
import { defaultLocale, formatDateOnly, formatMoney, localePackageSchema } from "./package";
Font.register({ family: "LocaleArabic", fonts: [
 { src: path.join(process.cwd(), "public/fonts/NotoNaskhArabic-Regular.ttf"), fontWeight: 400 },
 { src: path.join(process.cwd(), "public/fonts/NotoNaskhArabic-Bold.ttf"), fontWeight: 700 },
] });
const labels = {
 ur: {"invoice":"فیس کا بل","student":"طالب علم","roll":"رول نمبر","class":"جماعت","date":"بل کی تاریخ","due":"آخری تاریخ","monthlyFee":"ماہانہ فیس","oneTimeFees":"یک وقتی فیس","subtotal":"ذیلی مجموعہ","discountAmount":"رعایت","lateFeeAmount":"تاخیر کی فیس","taxAmount":"ٹیکس","totalAmount":"کل رقم","totalAmountPaid":"ادا شدہ رقم","balanceDue":"باقی رقم","signature":"مجاز دستخط","original":"بنیادی عیسوی تاریخ","generated":"تیار کردہ"},
 en: { invoice: "Fee invoice", student: "Student", roll: "Roll number", class: "Class", date: "Invoice date", due: "Due date", monthlyFee: "Monthly fee", oneTimeFees: "One-time fees", subtotal: "Subtotal", discountAmount: "Discount", lateFeeAmount: "Late fee", taxAmount: "Tax", totalAmount: "Total", totalAmountPaid: "Total paid", balanceDue: "Balance due", signature: "Authorized signature", original: "Underlying Gregorian date", generated: "Generated by" },
 ar: { invoice: "فاتورة الرسوم", student: "الطالب", roll: "رقم الطالب", class: "الصف", date: "تاريخ الفاتورة", due: "تاريخ الاستحقاق", monthlyFee: "الرسوم الشهرية", oneTimeFees: "رسوم لمرة واحدة", subtotal: "المجموع الفرعي", discountAmount: "الخصم", lateFeeAmount: "رسوم التأخير", taxAmount: "الضريبة", totalAmount: "الإجمالي", totalAmountPaid: "إجمالي المدفوع", balanceDue: "الرصيد المستحق", signature: "التوقيع المعتمد", original: "التاريخ الميلادي الأساسي", generated: "تم الإنشاء بواسطة" },
};
type InvoiceDocument = { invoiceNumber: string | null; currency: string; localeSnapshot: unknown; invoiceDate: Date; dueDate: Date; campus: { name: string }; student: { fullName: string; rollNo: string; class: { name: string; section: string | null } }; monthlyFee: number; oneTimeFees: number; subtotal: number; discountAmount: number; lateFeeAmount: number; taxAmount: number; totalAmount: number; totalAmountPaid: number; balanceDue: number };
const styles = StyleSheet.create({ page: { padding: 36, fontSize: 12, color: "#172033", fontFamily: "LocaleArabic" }, heading: { fontSize: 22, fontWeight: 700, marginBottom: 8 }, row: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#ddd", paddingVertical: 7, gap: 18 }, label: { flex: 1 }, value: { flex: 1 }, muted: { fontSize: 9, color: "#667085", marginTop: 12 } });
export function renderLocaleInvoice(invoice: InvoiceDocument) {
 const parsed = localePackageSchema.safeParse(invoice.localeSnapshot);
 const policy = parsed.success ? parsed.data : defaultLocale;
 const t = labels[policy.language]; const rtl = policy.language !== "en";
 const rows: [string, string][] = [
 [t.student, invoice.student.fullName], [t.roll, invoice.student.rollNo], [t.class, [invoice.student.class.name, invoice.student.class.section].filter(Boolean).join(" ")],
 [t.date, formatDateOnly(invoice.invoiceDate.toISOString().slice(0, 10), policy)], [t.due, formatDateOnly(invoice.dueDate.toISOString().slice(0, 10), policy)],
 ...(["monthlyFee", "oneTimeFees", "subtotal", "discountAmount", "lateFeeAmount", "taxAmount", "totalAmount", "totalAmountPaid", "balanceDue"] as const).map((key): [string, string] => [t[key], formatMoney({ minor: invoice[key], currency: invoice.currency }, policy)]),
 ];
 return renderToBuffer(<Document language={policy.language}><Page size="A4" style={[styles.page, { direction: rtl ? "rtl" : "ltr", textAlign: rtl ? "right" : "left" }]}><Text style={styles.heading}>{invoice.campus.name}</Text><Text style={styles.heading}>{t.invoice}</Text><Text>{invoice.invoiceNumber || "—"}</Text>{rows.map(([label, value]) => <View key={label} style={[styles.row, { flexDirection: rtl ? "row-reverse" : "row" }]}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}<Text style={styles.muted}>{t.original}</Text><Text style={[styles.muted, { direction: "ltr", textAlign: "left" }]}>{invoice.invoiceDate.toISOString().slice(0, 10)} / {invoice.dueDate.toISOString().slice(0, 10)}</Text><Text style={styles.muted}>{t.signature}: ____________________</Text><View style={[styles.row, { borderBottomWidth: 0 }]}><Text style={[styles.muted, { direction: "ltr" }]}>SkooleeAI</Text><Text style={styles.muted}>{t.generated}</Text></View></Page></Document>);
}
