import type { Language } from "./package";
const en = {
  title: "Language and regional settings", help: "Preview before applying to your school. Display changes never convert stored amounts or identities.",
  personal: "My display language", inherit: "Inherit school or campus language", scope: "Settings scope", school: "School defaults", group: "School-group defaults", inherited: "Inherited from school", override: "Override this setting", delegated: "Delegated campus settings", delegationHelp: "Only checked fields can be changed by this campus administrator or principal.",
  language: "Default language", timezone: "IANA timezone", calendar: "Calendar display", numberingSystem: "Digits", currency: "Currency display package", weekStartsOn: "First weekday", weekend: "Weekend days", effectiveDate: "Effective date (YYYY-MM-DD, 00:00 UTC)",
  preview: "Preview changes", reset: "Reset draft", apply: "Apply reviewed settings", preparing: "Preparing interface and document samples…", save: "Save", saved: "Locale settings saved for the selected effective date.", pending: "Currency change awaits independent finance review.", permission: "School settings access or delegated campus permission is required.", timezoneError: "This timezone is unsupported. Choose a valid IANA timezone.", error: "Unable to save. Check the fields and try again.", futureDate: "Choose a future effective date.", stale: "Settings changed since preview. Preview again before applying.",
  dateHelp: "Gregorian and ISO 8601 display only. Stored dates remain Gregorian. No unvalidated calendar conversion is offered.", moneyHelp: "Existing records retain their currency and integer minor units. Currency changes require finance review. No automatic conversion.",
  attendance: "Attendance date", birthday: "Date of birth", invoice: "Invoice", report: "Report", notification: "Notification", print: "Print or save as PDF", before: "Current display", after: "Proposed display", schedule: "Future event (same stored UTC instant)", historical: "Historical event (original timezone retained)", original: "Underlying Gregorian date", synthetic: "Synthetic formatting sample; translation approval is still required.", review: "Pending finance review", approve: "Approve currency", reject: "Reject currency", active: "Scheduled / active", empty: "Choose a locale package to preview your school’s formats.", inheritedField: "Use school value", days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
};
type Catalog = { [K in keyof typeof en]: typeof en[K] extends string[] ? string[] : string };
const ar: Catalog = {
  title: "إعدادات اللغة والمنطقة", help: "عاين الإعدادات قبل تطبيقها على المدرسة. لا يغيّر العرض المبالغ المخزنة أو الهويات.",
  personal: "لغة العرض الشخصية", inherit: "استخدام لغة المدرسة أو الحرم", scope: "نطاق الإعدادات", school: "إعدادات المدرسة", group: "إعدادات مجموعة المدارس", inherited: "موروث من المدرسة", override: "تجاوز هذا الإعداد", delegated: "إعدادات الحرم المفوضة", delegationHelp: "يمكن لمسؤول الحرم أو المدير تغيير الحقول المحددة فقط.",
  language: "اللغة الافتراضية", timezone: "المنطقة الزمنية IANA", calendar: "عرض التقويم", numberingSystem: "الأرقام", currency: "حزمة عرض العملة", weekStartsOn: "أول أيام الأسبوع", weekend: "أيام العطلة الأسبوعية", effectiveDate: "تاريخ السريان (YYYY-MM-DD، الساعة 00:00 UTC)",
  preview: "معاينة التغييرات", reset: "إعادة تعيين المسودة", apply: "تطبيق الإعدادات المراجعة", preparing: "جارٍ إعداد نماذج الواجهة والمستندات…", save: "حفظ", saved: "تم حفظ إعدادات اللغة لتاريخ السريان المحدد.", pending: "تغيير العملة بانتظار مراجعة مالية مستقلة.", permission: "يلزم إذن إعدادات المدرسة أو تفويض الحرم.", timezoneError: "المنطقة الزمنية غير مدعومة. اختر منطقة IANA صالحة.", error: "تعذر الحفظ. تحقق من الحقول وحاول مجددًا.", futureDate: "اختر تاريخ سريان مستقبليًا.", stale: "تغيرت الإعدادات بعد المعاينة. أعد المعاينة قبل التطبيق.",
  dateHelp: "عرض التقويم الميلادي وISO 8601 فقط. تبقى التواريخ المخزنة ميلادية. لا تتوفر تحويلات تقويم غير معتمدة.", moneyHelp: "تحتفظ السجلات الحالية بعملتها ووحداتها الصغرى الصحيحة. يلزم تغيير العملة مراجعة مالية. لا يوجد تحويل تلقائي.",
  attendance: "تاريخ الحضور", birthday: "تاريخ الميلاد", invoice: "فاتورة", report: "تقرير", notification: "إشعار", print: "طباعة أو حفظ PDF", before: "العرض الحالي", after: "العرض المقترح", schedule: "حدث مستقبلي (نفس اللحظة المخزنة بتوقيت UTC)", historical: "حدث سابق (المنطقة الزمنية الأصلية محفوظة)", original: "التاريخ الميلادي الأساسي", synthetic: "نموذج تنسيق تجريبي؛ ما زالت الترجمة بحاجة إلى اعتماد.", review: "بانتظار المراجعة المالية", approve: "اعتماد العملة", reject: "رفض العملة", active: "مجدول / نشط", empty: "اختر حزمة اللغة لمعاينة تنسيقات المدرسة.", inheritedField: "استخدام قيمة المدرسة", days: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
};
export const catalogs = { en, ar };
export function messages(language: Language) { return catalogs[language]; }
