import type { NotificationTemplateKey } from "@/lib/notifications/templates";
export const arabicNotificationCopy: Record<NotificationTemplateKey, { title: string; subject: string; body: string }> = {
 ATTENDANCE_ALERT: { title: "تنبيه الحضور", subject: "تنبيه الحضور للطالب {{studentName}}", body: "عزيزي {{parentName}}،\n\nسُجل غياب {{studentName}} بتاريخ {{date}}. عدد مرات الغياب في الفترة الأخيرة: {{absenceCount}}.\n\nيرجى التواصل مع {{campusName}} للمساعدة.\n\n{{schoolName}}" },
 FEE_DUE_REMINDER: { title: "تذكير بالرسوم", subject: "تذكير برسوم {{studentName}}", body: "عزيزي {{parentName}}،\n\nنذكركم بأن رسوم {{studentName}} عن {{term}} بمبلغ {{balanceDue}} تستحق بتاريخ {{dueDate}}.\n\nيرجى تجاهل الرسالة إذا تم الدفع.\n\n{{schoolName}}" },
 FEE_OVERDUE_REMINDER: { title: "تذكير برسوم متأخرة", subject: "رسوم متأخرة للطالب {{studentName}}", body: "عزيزي {{parentName}}،\n\nتأخر سداد رسوم {{studentName}} عن {{term}} بمبلغ {{balanceDue}} المستحقة بتاريخ {{dueDate}}.\n\nيرجى التواصل مع {{campusName}} للمساعدة في الدفع.\n\n{{schoolName}}" },
 EXAM_SCHEDULE: { title: "جدول الاختبارات", subject: "جدول اختبارات {{studentName}}", body: "عزيزي {{parentName}}،\n\nتم تحديد {{examTitle}} للصف {{className}} للفصل {{term}} من العام الدراسي {{academicYear}}. يرجى مساعدة {{studentName}} في الاستعداد واتباع تعليمات الحرم.\n\n{{schoolName}}" },
 REPORT_CARD_PUBLISHED: { title: "نشر التقرير الدراسي", subject: "تقرير {{studentName}} جاهز", body: "عزيزي {{parentName}}،\n\nتم نشر تقرير {{studentName}} لاختبار {{examTitle}}.\n\nالتقدير: {{grade}}\nالنسبة: {{percentage}}%\n\n{{viewInstruction}}\n\n{{schoolName}}" },
 PARENT_MEETING_INVITE: { title: "دعوة لاجتماع أولياء الأمور", subject: "دعوة لاجتماع أولياء الأمور", body: "عزيزي {{parentName}}،\n\nندعوكم لاجتماع بخصوص {{studentName}} بتاريخ {{meetingDate}} الساعة {{meetingTime}}.\n\nالمكان: {{meetingLocation}}\n\n{{schoolName}}" },
 GENERAL_ANNOUNCEMENT: { title: "إعلان عام", subject: "{{announcementTitle}}", body: "عزيزي {{parentName}}،\n\n{{announcementBody}}\n\n{{schoolName}}" },
 MARKS_ENTRY_DEADLINE_NEAR: { title: "اقتراب موعد إدخال الدرجات", subject: "اقتراب موعد إدخال الدرجات", body: "عزيزي {{recipientName}}،\n\nآخر موعد لإدخال درجات {{examTitle}} هو {{deadlineDate}}. يرجى إكمال الدرجات المتبقية للصف {{className}}.\n\n{{schoolName}}" },
 PRINCIPAL_REVIEW_PENDING: { title: "بانتظار مراجعة المدير", subject: "مراجعة المدير لاختبار {{examTitle}}", body: "عزيزي {{recipientName}}،\n\nتقارير {{examTitle}} للصف {{className}} جاهزة لمراجعة المدير.\n\nالتقارير المتبقية: {{pendingCount}}\n\n{{schoolName}}" },
 REPORT_CARD_GENERATED: { title: "إنشاء التقارير الدراسية", subject: "تم إنشاء تقارير {{examTitle}}", body: "عزيزي {{recipientName}}،\n\nتم إنشاء تقارير {{examTitle}} وهي بانتظار المراجعة والنشر.\n\nعدد التقارير: {{reportCount}}\n\n{{schoolName}}" },
};
export function notificationHtml(body: string, language: "en" | "ar" | "ur") {
 const escaped = body.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
 return `<div lang="${language}" dir="${language !== "en" ? "rtl" : "ltr"}" style="white-space:pre-wrap;text-align:${language !== "en" ? "right" : "left"}">${escaped}</div>`;
}
export const urduNotificationCopy: typeof arabicNotificationCopy = {
 ATTENDANCE_ALERT: { title: "حاضری کی اطلاع", subject: "{{studentName}} کی حاضری کی اطلاع", body: "محترم {{parentName}}،\n\n{{studentName}} کی غیر حاضری {{date}} کو درج ہوئی۔ حالیہ غیر حاضریوں کی تعداد: {{absenceCount}}۔\n\nمدد کے لیے {{campusName}} سے رابطہ کریں۔\n\n{{schoolName}}" },
 FEE_DUE_REMINDER: { title: "فیس کی یاد دہانی", subject: "{{studentName}} کی فیس کی یاد دہانی", body: "محترم {{parentName}}،\n\n{{studentName}} کی {{term}} کی فیس {{balanceDue}} ہے، جس کی آخری تاریخ {{dueDate}} ہے۔\n\nادائیگی ہو چکی ہو تو یہ پیغام نظر انداز کریں۔\n\n{{schoolName}}" },
 FEE_OVERDUE_REMINDER: { title: "واجب الادا فیس کی یاد دہانی", subject: "{{studentName}} کی تاخیر شدہ فیس", body: "محترم {{parentName}}،\n\n{{studentName}} کی {{term}} کی فیس {{balanceDue}}، جس کی آخری تاریخ {{dueDate}} تھی، ابھی باقی ہے۔\n\nادائیگی میں مدد کے لیے {{campusName}} سے رابطہ کریں۔\n\n{{schoolName}}" },
 EXAM_SCHEDULE: { title: "امتحانات کا شیڈول", subject: "{{studentName}} کا امتحانی شیڈول", body: "محترم {{parentName}}،\n\nتعلیمی سال {{academicYear}} کی مدت {{term}} میں جماعت {{className}} کا {{examTitle}} طے ہو گیا ہے۔ براہ کرم {{studentName}} کی تیاری میں مدد کریں اور کیمپس کی ہدایات پر عمل کریں۔\n\n{{schoolName}}" },
 REPORT_CARD_PUBLISHED: { title: "رپورٹ کارڈ شائع ہو گیا", subject: "{{studentName}} کی رپورٹ تیار ہے", body: "محترم {{parentName}}،\n\n{{studentName}} کا {{examTitle}} کا رپورٹ کارڈ شائع ہو گیا ہے۔\n\nگریڈ: {{grade}}\nفیصد: {{percentage}}%\n\n{{viewInstruction}}\n\n{{schoolName}}" },
 PARENT_MEETING_INVITE: { title: "والدین کی ملاقات کی دعوت", subject: "والدین کی ملاقات کی دعوت", body: "محترم {{parentName}}،\n\n{{studentName}} کے بارے میں ملاقات کے لیے {{meetingDate}} کو {{meetingTime}} پر تشریف لائیں۔\n\nمقام: {{meetingLocation}}\n\n{{schoolName}}" },
 GENERAL_ANNOUNCEMENT: { title: "عام اعلان", subject: "{{announcementTitle}}", body: "محترم {{parentName}}،\n\n{{announcementBody}}\n\n{{schoolName}}" },
 MARKS_ENTRY_DEADLINE_NEAR: { title: "نمبر درج کرنے کی آخری تاریخ قریب ہے", subject: "نمبر درج کرنے کی آخری تاریخ قریب ہے", body: "محترم {{recipientName}}،\n\n{{examTitle}} کے نمبر درج کرنے کی آخری تاریخ {{deadlineDate}} ہے۔ جماعت {{className}} کے باقی نمبر مکمل کریں۔\n\n{{schoolName}}" },
 PRINCIPAL_REVIEW_PENDING: { title: "پرنسپل کے جائزے کا منتظر", subject: "{{examTitle}} کا پرنسپل جائزہ", body: "محترم {{recipientName}}،\n\nجماعت {{className}} کے {{examTitle}} کی رپورٹیں پرنسپل کے جائزے کے لیے تیار ہیں۔\n\nباقی رپورٹیں: {{pendingCount}}\n\n{{schoolName}}" },
 REPORT_CARD_GENERATED: { title: "رپورٹ کارڈ تیار ہو گئے", subject: "{{examTitle}} کی رپورٹیں تیار ہو گئیں", body: "محترم {{recipientName}}،\n\n{{examTitle}} کی رپورٹیں تیار ہیں اور جائزے و اشاعت کی منتظر ہیں۔\n\nرپورٹوں کی تعداد: {{reportCount}}\n\n{{schoolName}}" },
};
